In [47]:
import pandas as pd
import numpy as np

In [48]:
data = "HDR 2007-2008 Table 11.xlsx"

df = pd.read_excel(data)
df.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,… to acquire knowledge ….,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11 Commitment to education: public spending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Public expenditure on education,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,As a % of GDP,NaN,NaN,NaN,As a % of total government expenditure,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,1991,NaN,2002-05 b,NaN,1991,NaN,2002-05 b,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,Iceland,NaN,..,NaN,8.1,NaN,..,NaN,16.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2,Norway,NaN,7.1,NaN,7.7,NaN,14.6,NaN,16.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3,Australia,NaN,4.9,NaN,4.7,NaN,14.8,NaN,13.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
Entête=df.loc[1:2,:]

In [52]:
Entête

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
1,11 Commitment to education: public spending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
baspage=df.loc[190:194,:]

In [60]:
baspage

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
190,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,a. Expenditures by level may not sum to 100 as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,"SOURCES\nColumns 1–4, 7, 9 and 10: UNESCO Inst...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df=pd.read_excel(data, header=3)
df=df.dropna(how="all", axis=1)
df=df.dropna(how="all", axis=0).reset_index(drop=True)
df.head(6)

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,Public expenditure on education,NaN,NaN,NaN,NaN,NaN,NaN,Current public expenditure on education by lev...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,As a % of GDP,NaN,NaN,As a % of total government expenditure,NaN,NaN,NaN,Pre-primary and primary,...,NaN,NaN,Secondary and post-secondary non-tertiary ...,NaN,NaN,NaN,Tertiary,NaN,NaN,NaN
2,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,1991,2002-05 b,NaN,1991,NaN,2002-05 b,NaN,1991,...,2002-05 b,NaN,1991,NaN,2002-05 b,NaN,1991,NaN,2002-05 b,NaN
4,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,Iceland,..,8.1,NaN,..,NaN,16.6,NaN,..,...,40,NaN,..,NaN,35,NaN,..,NaN,19,NaN

In [62]:
columns=[]
for c in df.columns:
    columns.append([str(v) for v in df[c][:5] if pd.notnull(v)])
columns

[['HDI rank', 'HIGH HUMAN DEVELOPMENT'],
 [],
 ['Public expenditure on education   ', 'As a % of GDP', '1991'],
 ['2002-05 b'],
 [],
 ['As a % of total government expenditure', '1991'],
 [],
 ['2002-05 b'],
 [],
 ['Current public expenditure on education by levela                                                                              (% of total current public expenditure on education) ',
  'Pre-primary                           and primary',
  '1991'],
 [],
 ['2002-05 b'],
 [],
 ['Secondary and post-secondary non-tertiary                    ', '1991'],
 [],
 ['2002-05 b'],
 [],
 ['Tertiary                          ', '1991'],
 [],
 ['2002-05 b'],
 []]

In [63]:
columns=[
    "HDI rank",
    "country",
    "Public expenditure on education-As a % of GDP-1991",
    "Public expenditure on education-As a % of GDP-2002-05",
    "Reference 1",
    "Public expenditure on education-As a % of total government expenditure-1991",
    "Reference 2",
    "Public expenditure on education-As a % of total government expenditure-2002-05",
    "Reference 3",
    "Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-1991",
    "Reference 4",
    "Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-2002-05",
    "Reference 5",
    "Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-1991",
    "Reference 6",
    "Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-2002-05",
    "Reference 7",
    "Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-1991",
    "Reference 8",
    "Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-2002-05",
    "Reference 9"
]
df.columns = columns
df = df.drop(np.arange(5), axis=0).reset_index(drop=True)
df.head()

,HDI rank,country,Public expenditure on education-As a % of GDP-1991,Public expenditure on education-As a % of GDP-2002-05,Reference 1,Public expenditure on education-As a % of total government expenditure-1991,Reference 2,Public expenditure on education-As a % of total government expenditure-2002-05,Reference 3,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-1991,...,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-2002-05,Reference 5,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-1991,Reference 6,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-2002-05,Reference 7,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-1991,Reference 8,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-2002-05,Reference 9
0,1,Iceland,..,8.1,NaN,..,NaN,16.6,NaN,..,...,40,NaN,..,NaN,35,NaN,..,NaN,19,NaN
1,2,Norway,7.1,7.7,NaN,14.6,NaN,16.6,NaN,38,...,28,NaN,27,NaN,35,NaN,16,NaN,33,NaN
2,3,Australia,4.9,4.7,NaN,14.8,NaN,13.3,c,..,...,34,NaN,..,NaN,41,NaN,..,NaN,25,NaN
3,4,Canada,6.5,5.2,NaN,14.2,NaN,12.5,c,..,...,..,NaN,68,NaN,..,NaN,31,NaN,34,e
4,5,Ireland,5.0,4.8,NaN,9.7,NaN,14.0,NaN,37,...,33,NaN,40,NaN,43,NaN,21,NaN,24,NaN

In [70]:
mycolumns=['Reference 1', 'Reference 2', 'Reference 3', 'Reference 4', 'Reference 5', 'Reference 6', 'Reference 7', 'Reference 8', 'Reference 9']
df[mycolumns]

,Reference 1,Reference 2,Reference 3,Reference 4,Reference 5,Reference 6,Reference 7,Reference 8,Reference 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,c,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,c,d,NaN,NaN,NaN,NaN,e
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,e,NaN,e,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,NaN,NaN,c,NaN,"c,e",NaN,"c,e",NaN,"c,e"

In [72]:
df.drop(['Reference 1', 'Reference 2', 'Reference 3', 'Reference 4', 'Reference 5', 'Reference 6', 'Reference 7', 'Reference 8', 'Reference 9'], axis=1, inplace=True)

In [73]:
df.tail(30)

,HDI rank,country,Public expenditure on education-As a % of GDP-1991,Public expenditure on education-As a % of GDP-2002-05,Public expenditure on education-As a % of total government expenditure-1991,Public expenditure on education-As a % of total government expenditure-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-2002-05,HDI category
95,96,Georgia,..,2.9,..,13.1,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
96,97,Guyana,2.2,8.5,6.5,14.5,..,44,..,13,..,4,LOW HUMAN DEVELOPMENT
97,98,Azerbaijan,7.7,2.5,24.7,19.6,..,25,..,56,..,6,LOW HUMAN DEVELOPMENT
98,99,Sri Lanka,3.2,..,8.4,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
99,100,Maldives,7.0,7.1,16.0,15.0,..,54,..,..,..,..,LOW HUMAN DEVELOPMENT
100,101,Jamaica,4.5,5.3,12.8,8.8,37,37,33,44,21,20,LOW HUMAN DEVELOPMENT
101,102,Cape Verde,3.6,6.6,19.9,25.4,..,54,..,36,..,10,LOW HUMAN DEVELOPMENT
102,103,El Salvador,1.8,2.8,15.2,20.0,..,60,..,29,..,11,LOW HUMAN DEVELOPMENT
103,104,Algeria,5.1,..,22.0,..,95,..,..,..,..,..,LOW HUMAN DEVELOPMENT
104,105,Viet Nam,1.8,..,9.7,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
105,106,Occupied Palestinian Territories,..,..,..,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
106,107,Indonesia,1.0,0.9,..,9.0,..,39,..,42,..,19,LOW HUMAN DEVELOPMENT
107,108,Syrian Arab Republic,3.9,..,14.2,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
108,109,Turkmenistan,3.9,..,19.7,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
109,110,Nicaragua,3.4,3.1,12.1,15.0,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
110,111,Moldova,5.3,4.3,21.6,21.1,..,36,..,55,..,9,LOW HUMAN DEVELOPMENT
111,112,Egypt,3.9,..,..,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
112,113,Uzbekistan,9.4,..,17.8,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
113,114,Mongolia,11.5,5.3,22.7,..,..,43,..,37,..,19,LOW HUMAN DEVELOPMENT
114,115,Honduras,3.8,..,..,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
115,116,Kyrgyzstan,6.0,4.4,22.7,18.6,..,23,..,46,..,19,LOW HUMAN DEVELOPMENT
116,117,Bolivia,2.4,6.4,..,18.1,..,49,..,25,..,23,LOW HUMAN DEVELOPMENT
117,118,Guatemala,1.3,..,13.0,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
118,119,Gabon,..,3.9,..,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
119,120,Vanuatu,4.6,9.6,18.8,26.7,..,44,..,41,..,9,LOW HUMAN DEVELOPMENT
120,121,South Africa,5.9,5.4,..,17.9,76,43,..,33,22,16,LOW HUMAN DEVELOPMENT
121,122,Tajikistan,9.1,3.5,24.4,18.0,..,31,..,54,..,5,LOW HUMAN DEVELOPMENT
122,123,Sao Tome and Principe,..,..,..,..,..,..,..,..,..,..,LOW HUMAN DEVELOPMENT
123,124,Botswana,6.2,10.7,17.0,21.5,..,25,..,41,..,32,LOW HUMAN DEVELOPMENT
124,125,Namibia,7.9,6.9,..,21.0,..,60,..,29,..,11,LOW HUMAN DEVELOPMENT

In [74]:
df=df.drop(np.arange(126,len(df)), axis=0).reset_index(drop=True)

In [96]:
hdi_categories = ["HIGH HUMAN DEVELOPMENT", "MEDIUM HUMAN DEVELOPMENT", "LOW HUMAN DEVELOPMENT"]
# Se débarrasser des rangées avec les catégories HDI
# https://stackoverflow.com/a/27360130 & https://stackoverflow.com/a/12098586
df = df.drop(df[df["HDI rank"].isin(hdi_categories)].index, axis=0).reset_index(drop=True)
# Référence pour np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
# Pensez que cela ressemble à une déclaration du type "if" : where(test est vrai, vrai-quelque chose, faux-quelque chose)
# ceci peut aussi être imbriqué : where(test is true, true-thing, where(new-test is true, true-thing, false-thing))
df.loc[:, "HDI category"] = np.where(df["HDI rank"] > 155,
                                     "LOW HUMAN DEVELOPMENT",
                                     np.where(df["HDI rank"] > 70,
                                              "MEDIUM HUMAN DEVELOPMENT",
                                              "HIGH HUMAN DEVELOPMENT"
                                             )
                                    )
df.sort_values(by="HDI rank", inplace=True)
df.head()

,HDI rank,country,Public expenditure on education-As a % of GDP-1991,Public expenditure on education-As a % of GDP-2002-05,Public expenditure on education-As a % of total government expenditure-1991,Public expenditure on education-As a % of total government expenditure-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-2002-05,HDI category
0,1,Iceland,..,8.1,..,16.6,..,40,..,35,..,19,HIGH HUMAN DEVELOPMENT
1,2,Norway,7.1,7.7,14.6,16.6,38,28,27,35,16,33,HIGH HUMAN DEVELOPMENT
2,3,Australia,4.9,4.7,14.8,13.3,..,34,..,41,..,25,HIGH HUMAN DEVELOPMENT
3,4,Canada,6.5,5.2,14.2,12.5,..,..,68,..,31,34,HIGH HUMAN DEVELOPMENT
4,5,Ireland,5.0,4.8,9.7,14.0,37,33,40,43,21,24,HIGH HUMAN DEVELOPMENT

In [97]:
df.tail(30)

,HDI rank,country,Public expenditure on education-As a % of GDP-1991,Public expenditure on education-As a % of GDP-2002-05,Public expenditure on education-As a % of total government expenditure-1991,Public expenditure on education-As a % of total government expenditure-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Pre-primary-and primary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Secondary and post-secondary non-tertiary-2002-05,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-1991,Current public expenditure on education by level (% of total current public expenditure on education) Tertiary-2002-05,HDI category
95,96,Georgia,..,2.9,..,13.1,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
96,97,Guyana,2.2,8.5,6.5,14.5,..,44,..,13,..,4,MEDIUM HUMAN DEVELOPMENT
97,98,Azerbaijan,7.7,2.5,24.7,19.6,..,25,..,56,..,6,MEDIUM HUMAN DEVELOPMENT
98,99,Sri Lanka,3.2,..,8.4,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
99,100,Maldives,7.0,7.1,16.0,15.0,..,54,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
100,101,Jamaica,4.5,5.3,12.8,8.8,37,37,33,44,21,20,MEDIUM HUMAN DEVELOPMENT
101,102,Cape Verde,3.6,6.6,19.9,25.4,..,54,..,36,..,10,MEDIUM HUMAN DEVELOPMENT
102,103,El Salvador,1.8,2.8,15.2,20.0,..,60,..,29,..,11,MEDIUM HUMAN DEVELOPMENT
103,104,Algeria,5.1,..,22.0,..,95,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
104,105,Viet Nam,1.8,..,9.7,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
105,106,Occupied Palestinian Territories,..,..,..,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
106,107,Indonesia,1.0,0.9,..,9.0,..,39,..,42,..,19,MEDIUM HUMAN DEVELOPMENT
107,108,Syrian Arab Republic,3.9,..,14.2,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
108,109,Turkmenistan,3.9,..,19.7,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
109,110,Nicaragua,3.4,3.1,12.1,15.0,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
110,111,Moldova,5.3,4.3,21.6,21.1,..,36,..,55,..,9,MEDIUM HUMAN DEVELOPMENT
111,112,Egypt,3.9,..,..,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
112,113,Uzbekistan,9.4,..,17.8,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
113,114,Mongolia,11.5,5.3,22.7,..,..,43,..,37,..,19,MEDIUM HUMAN DEVELOPMENT
114,115,Honduras,3.8,..,..,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
115,116,Kyrgyzstan,6.0,4.4,22.7,18.6,..,23,..,46,..,19,MEDIUM HUMAN DEVELOPMENT
116,117,Bolivia,2.4,6.4,..,18.1,..,49,..,25,..,23,MEDIUM HUMAN DEVELOPMENT
117,118,Guatemala,1.3,..,13.0,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
118,119,Gabon,..,3.9,..,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
119,120,Vanuatu,4.6,9.6,18.8,26.7,..,44,..,41,..,9,MEDIUM HUMAN DEVELOPMENT
120,121,South Africa,5.9,5.4,..,17.9,76,43,..,33,22,16,MEDIUM HUMAN DEVELOPMENT
121,122,Tajikistan,9.1,3.5,24.4,18.0,..,31,..,54,..,5,MEDIUM HUMAN DEVELOPMENT
122,123,Sao Tome and Principe,..,..,..,..,..,..,..,..,..,..,MEDIUM HUMAN DEVELOPMENT
123,124,Botswana,6.2,10.7,17.0,21.5,..,25,..,41,..,32,MEDIUM HUMAN DEVELOPMENT
124,125,Namibia,7.9,6.9,..,21.0,..,60,..,29,..,11,MEDIUM HUMAN DEVELOPMENT

In [80]:
destination="education_public_spending_per_level_of_HDI.csv"
df.to_csv(destination, index=False)